export enum CallToActions {
  COMPLETE_COMPANY_PROFILE_AND_UPGRADE_SUBSCRIPTION_PLAN = 0,
  COMPLETE_COMPANY_PROFILE = 1,
  UPGRADE_SUBSCRIPTION_PLAN = 2,
  COMPANY_ADD_PAYMENT_DETAILS_TO_UNLOCK_MORE_FEATURES = 3,
  COMPANY_SUBSCRIPTION_OUTSTANDING = 4,
  COMPANY_OWNERSHIP_NEEDS_CONFIRMATION = 5,
  MOD_PRODUCT_READY_FOR_SALE = 6,
  CREATE_STORE_FOR_SELLING = 7,
  COMPANY_NEEDS_TO_ADD_PAYMENT_METHOD = 8,
  YOUR_COMPANIES_NEED_STRIPE_TO_COLLECT_PAYMENT = 9,
  SUPPLIER_PRODUCT_READY_FOR_SALE = 10,
  SET_PASSWORD = 11,
}
