export enum CallToActions {
  COMPLETE_COMPANY_PROFILE_AND_UPGRADE_SUBSCRIPTION_PLAN = 0,
  COMPLETE_COMPANY_PROFILE = 1,
  UPGRADE_SUBSCRIPTION_PLAN = 2,
  COMPANY_ADD_PAYMENT_DETAILS_TO_UNLOCK_MORE_FEATURES = 3,
}
