export enum DomainType {
  UNRESTRICTED = 0,
  SELLER = 1,
  SELLER_PLUS = 2,
  SUPPLIER = 3,
  RESTRICTED_SUPPLIER = 4,
  DOMAIN_SUPPLIER = 5,
  DOMAIN_CLIENT_CATALOGUE = 6,
  DOMAIN_SHOPIFY_SELLER = 7,
  UNRESTRICTED_SHOPIFY_APP = 8,
  RESERVED = 9,
}
