export enum JobType {
  PRODUCT_CREATION_MOD = 0, // SUPPLIER_MOD, CLONED_SUPPLIER_MOD
  PRODUCT_CREATION = 1, // SUPPLIER, // CLONED_SUPPLIER
  PRODUCT_RESELL_CREATION_MOD = 2, // SUPPLIER_RESELL_MOD, CLONED_SUPPLIER_RESELL_MOD
  PRODUCT_RESELL_CREATION = 3, // SUPPLIER_RESELL, CLONED_SUPPLIER_RESELL
  SELLER = 4, // SELLER, INVENTORY_SELLER, CLONED_INVENTORY_SELLER
  SELLER_MOD = 5, // CLONED_SELLER_MOD
  SELLER_GROUP_BUY = 6, // SELLER_GROUP_BUY, CLONED_SELLER_GROUP_BUY_INVENTORY
  SELLER_FILE_DOWNLOAD = 7, // SELLER_FILE_DOWNLOAD
  SUPPLIER_FULFILLMENT = 8, // PRODUCTION_MOD // SUPPLY_DOMAIN_REFERENCE
  SUPPLIER_FULFILLMENT_RESELL = 9, // SUPPLIER_TO_SUPPLIER_RESELL_MOD
  SUPPLIER_FULFILLMENT_INVENTORY = 10, // INVENTORY_SUPPLIER
  SUPPLIER_FULFILLMENT_INVENTORY_GROUP_BUY = 11, // SUPPLIER_GROUP_BUY_INVENTORY
  SUPPLY_CHAIN_CREATION = 12 // USED TO ID JOBS WHICH ARE TO CREATE A NEW SUPPLY CHAIN
}
