export enum ProductType {
  MOD = 0,
  MOQ = 1,
  SELLER = 2,
  SELLER_MOD = 3,
  CHAINED_MOD = 4,
  CHAINED_SELLER_MOD = 5,
  PRODUCTION_MOD = 6,
  CHAINED_MOQ = 7,
  INVENTORY_SELLER = 8,
  INVENTORY_SUPPLIER = 9,
}
