export enum ShipmentCompany {
  DHL = 0,
  UPS = 1,
  EMS = 2,
  FED_EX = 3,
  AUSTRALIA_POST = 4,
  STAR_TRACK = 5,
  TOLL = 6,
  TNT = 7,
  CUSTOM_TRACK_LINK = 8,
  ARAMEX = 9,
  REALTIME_EXPRESS = 10,
  UBER = 11,
  CIVIC_TRANSPORT_COURIERS = 12,
  NZ_POST = 13,
  SENDLE = 14,
  USPS = 15,
}
