export enum ProductionStatus {
  INIT = 0,
  REJECTED = 1,
  QUOTING = 2,
  ASSIGN_SENT = 3,
  ASSIGN_DEADLINE_REACHED = 5,
  QUESTIONING = 6,
  COMMENCED = 7,
  FINISHED = 8,
  SHIPPED = 9,
  COMPLETED = 10,
}
