export enum ShipmentStatus {
  NOT_ASSIGNED = 0,
  ASSIGNED = 1,
  DISPATCH_SET = 2,
  DISPATCH_WARNING = 3,
  DISPATCH_LATE = 4,
  DISPATCHED = 5,
  EXPECTED_RECEIVE_DATE_WARNING = 6,
  EXPECTED_RECEIVE_DATE_PAST = 7,
  RECEIVED = 8
}
