PRODUCT_CREATION_MOD = 0
PRODUCT_CREATION = 1
PRODUCT_RESELL_CREATION_MOD = 2
PRODUCT_RESELL_CREATION = 3
SELLER = 4
SELLER_MOD = 5
SELLER_GROUP_BUY = 6
SELLER_FILE_DOWNLOAD = 7
SUPPLIER_FULFILLMENT = 8
SUPPLIER_FULFILLMENT_RESELL = 9
SUPPLIER_FULFILLMENT_INVENTORY = 10
SUPPLIER_FULFILLMENT_INVENTORY_GROUP_BUY = 11

ALL_JOB_TYPES = [
    (PRODUCT_CREATION_MOD, "PRODUCT_CREATION_MOD"),
    (PRODUCT_CREATION, "PRODUCT_CREATION"),
    (PRODUCT_RESELL_CREATION_MOD, "PRODUCT_RESELL_CREATION_MOD"),
    (PRODUCT_RESELL_CREATION, "PRODUCT_RESELL_CREATION"),
    (SELLER, "SELLER"),
    (SELLER_MOD, "SELLER_MOD"),
    (SELLER_GROUP_BUY, "SELLER_GROUP_BUY"),
    (SELLER_FILE_DOWNLOAD, "SELLER_FILE_DOWNLOAD"),
    (SUPPLIER_FULFILLMENT, "SUPPLIER_FULFILLMENT"),
    (SUPPLIER_FULFILLMENT_RESELL, "SUPPLIER_FULFILLMENT_RESELL"),
    (SUPPLIER_FULFILLMENT_INVENTORY,
        "SUPPLIER_FULFILLMENT_INVENTORY"),
    (SUPPLIER_FULFILLMENT_INVENTORY_GROUP_BUY,
        "SUPPLIER_FULFILLMENT_INVENTORY_GROUP_BUY"),
]

JOB_TYPE_STRINGS = dict(ALL_JOB_TYPES)
