NO_TYPE = 0  # System
DRAFT_SENT = 1  # User
DRAFT_CHANGE_REQUEST = 2  # User
DRAFT_APPROVED = 3  # User
DESIGNER_ASSIGNED = 4  # Store
DESIGNER_CHANGED = 5  # Store
DRAFT_COMMENT = 6  # User
JOB_PAID = 7  # User / Store
INVOICE_PAID = 8  # User / Store
PAYMENT_ACCEPTED = 9  # User / Store
SEND_INVOICE = 10  # Store
JOB_COMMENT = 11  # User
PRODUCTION_COMMENT = 12  # User
JOB_STALE = 13  # Store
MANAGER_ASSIGNED = 14  # Store
ORDER_RECEIVED = 15  # Store
CLIENT_CHANGED = 16  # Store
PRODUCTION_FILE_UPLOADED = 17  # User
PRODUCTION_CANCELLED = 18  # Store
PRODUCTION_FINISHED = 19  # User
PRODUCTION_COMMENCED = 20  # User
QUOTE_APPROVED = 21  # User When quote has been approved by manager
QUOTE_REFUSED = 22  # User
QUOTE_SUBMITTED = 23  # User
QUOTE_FAILED = 24  # Store
QUOTE_COMMENCED = 25  # Store
QUOTE_EXPIRED = 26  # Store
SUPPLIER_ASSIGNED = 27  # Store
SUPPLIER_REFUSED = 28  # User
READY_FOR_SHIPPING = 29  # Store
SHIPMENT_UPDATE = 30  # User
SIGN_UP_CONFIRMATION = 31  # Store / System
AUTOMATIC_JOB_RESPONSE = 32  # User / Store
CRASH_EVENT = 33  # System
MANAGER_SUMMARY = 34  # System
PASSWORD_RESET = 35  # System
MANAGER_REASSIGNED = 36  # Store
EMAIL_RESPONSE = 37  # Store / System
JOB_NOTIFICATION = 38  # User / Store
JOB_REMINDER = 39  # User / Store
GENERAL_REMINDER = 40  # User / Store
INVOICE_EMAIL_RESPONSE = 41  # User / Store
AUTOMATIC_INVOICE_RESPONSE = 42  # User / Store
SHIPMENT_DISPATCH_CLOSE = 43  # Store / User
SHIPMENT_NOT_DISPATCHED = 44  # Store / User
SHIPMENT_EXPECTED_DATE_WARNING = 45  # Store / User
JOB_ADDED_TO_SHIPMENT = 46  # User / Store
JOB_REMOVED_FROM_SHIPMENT = 47  # User / Store
ASSIGNMENT_REMOVED_FROM_SHIPMENT = 48  # User / Store
ASSIGNMENT_ADDED_TO_SHIPMENT = 49  # User / Store
SHIPMENT_EXPECTED_DATE_PAST = 50  # Store / User
JOB_FILE_UPLOADED = 51  # User
STORE_INVITATION = 52  # Store
QUOTE_JOB_SUBMITTED = 53  # User
QUOTE_JOB_RECEIVED = 54  # User
QUOTE_JOB_UPDATED = 55  # User
QUOTE_JOB_UPDATED_SENT = 56  # User
QUOTE_JOB_APPROVED = 57  # User
QUOTE_JOB_APPROVED_SENT = 58  # User
JOB_NOTIFICATION_COMMENT = 59  # User
PRODUCTION_SHIPPED = 60  # User
SELLER_STORE_CREATED = 61  # System

SHOW_USER_AVATAR = \
    [DRAFT_SENT, DRAFT_CHANGE_REQUEST, DRAFT_APPROVED,
     DRAFT_COMMENT, JOB_COMMENT, PRODUCTION_COMMENT,
     PRODUCTION_FILE_UPLOADED, PRODUCTION_FINISHED, PRODUCTION_SHIPPED,
     PRODUCTION_COMMENCED, QUOTE_APPROVED, SHIPMENT_UPDATE,
     JOB_FILE_UPLOADED, QUOTE_JOB_SUBMITTED, QUOTE_JOB_RECEIVED,
     QUOTE_JOB_UPDATED, QUOTE_JOB_UPDATED_SENT,
     QUOTE_JOB_APPROVED, QUOTE_JOB_APPROVED_SENT,
     JOB_NOTIFICATION_COMMENT]

SHOW_STORE_AVATAR = \
    [NO_TYPE, DESIGNER_ASSIGNED, DESIGNER_CHANGED,
     SEND_INVOICE, JOB_STALE, MANAGER_ASSIGNED, ORDER_RECEIVED,
     CLIENT_CHANGED, PRODUCTION_CANCELLED, QUOTE_FAILED,
     QUOTE_COMMENCED, QUOTE_EXPIRED, SUPPLIER_ASSIGNED,
     READY_FOR_SHIPPING, SIGN_UP_CONFIRMATION, CRASH_EVENT,
     MANAGER_SUMMARY, PASSWORD_RESET, MANAGER_REASSIGNED,
     EMAIL_RESPONSE, SHIPMENT_EXPECTED_DATE_PAST, STORE_INVITATION,
     SELLER_STORE_CREATED]

SHOW_USER_OR_STORE_AVATAR = \
    [JOB_PAID, INVOICE_PAID, PAYMENT_ACCEPTED,
     AUTOMATIC_JOB_RESPONSE, JOB_NOTIFICATION,
     JOB_REMINDER, GENERAL_REMINDER,
     INVOICE_EMAIL_RESPONSE, AUTOMATIC_INVOICE_RESPONSE,
     JOB_ADDED_TO_SHIPMENT, JOB_REMOVED_FROM_SHIPMENT,
     ASSIGNMENT_REMOVED_FROM_SHIPMENT,
     SHIPMENT_EXPECTED_DATE_PAST,
     ASSIGNMENT_ADDED_TO_SHIPMENT]

SHOW_STORE_OR_USER_AVATAR = \
    [SHIPMENT_DISPATCH_CLOSE, SHIPMENT_NOT_DISPATCHED,
     SHIPMENT_EXPECTED_DATE_WARNING, SHIPMENT_EXPECTED_DATE_PAST]
