MOD = 0
MOQ = 1
SELLER = 2
SELLER_MOD = 3
CHAINED_MOD = 4
CHAINED_SELLER_MOD = 5
PRODUCTION_MOD = 6
CHAINED_MOQ = 7
INVENTORY_SELLER = 8
INVENTORY_SUPPLIER = 9

ALL_TYPES = [
    (MOD, "MOD"),
    (MOQ, "MOQ"),
    (SELLER, "SELLER"),
    (SELLER_MOD, "SELLER_MOD"),
    (CHAINED_MOD, "CHAINED_MOD"),
    (CHAINED_SELLER_MOD, "CHAINED_SELLER_MOD"),
    (PRODUCTION_MOD, "PRODUCTION_MOD"),
    (CHAINED_MOQ, "CHAINED_MOQ"),
    (INVENTORY_SELLER, "INVENTORY_SELLER"),
    (INVENTORY_SUPPLIER, "INVENTORY_SUPPLIER")
]
