SUPPLIER_MOD = 0
SUPPLIER = 1
SELLER = 2
SELLER_MOD = 3
CHAINED_MOD = 4
CHAINED_SELLER_MOD = 5
PRODUCTION_MOD = 6
CHAINED_SUPPLIER = 7
INVENTORY_SELLER = 8
INVENTORY_SUPPLIER = 9
SELLER_GROUP_BUY = 10
SUPPLIER_RESELL_MOD = 11
SUPPLIER_RESELL = 12

ALL_TYPES = [
    (SUPPLIER_MOD, "SUPPLIER_MOD"),
    (SUPPLIER, "SUPPLIER"),
    (SELLER, "SELLER"),
    (SELLER_MOD, "SELLER_MOD"),
    (CHAINED_MOD, "CHAINED_MOD"),
    (CHAINED_SELLER_MOD, "CHAINED_SELLER_MOD"),
    (PRODUCTION_MOD, "PRODUCTION_MOD"),
    (CHAINED_SUPPLIER, "CHAINED_SUPPLIER"),
    (INVENTORY_SELLER, "INVENTORY_SELLER"),
    (INVENTORY_SUPPLIER, "INVENTORY_SUPPLIER"),
    (SELLER_GROUP_BUY, "SELLER_GROUP_BUY"),
    (SELLER_GROUP_BUY, "SUPPLIER_RESELL_MOD"),
    (SELLER_GROUP_BUY, "SUPPLIER_RESELL")
]

TYPE_STRINGS = dict(ALL_TYPES)
