# ----
# Site

title: Merchi SDK
description: Merchi SDK and Protocol Documentation
url: https://merchisdk.github.io/sdk/
google_analytics_key:
permalink: pretty
baseurl:

# -----
# Build

timezone: Etc/UTC

collections:
  overview:
    title: Overview
    position: 1
  typescript:
    title: Typescript SDK
    position: 2
  javascript:
    title: Javascript SDK
    position: 3
  python:
    title: Python
    position: 4
  php:
    title: PHP
    position: 5
  filters:
    title: Filter Reference
    position: 6
  protocol:
    title: Protocol
    position: 7
  entities:
    title: Entity Reference
    position: 8
plugins:
  - jekyll-sitemap

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "api"
    values:
      _hide_content: true

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
