name: build docs
on:
  push:
    branches:
      - master
defaults:
  run:
    working-directory: typescript
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt install nodejs
      - run: yarn
      - run: yarn add --dev typescript
      - run: yarn add --dev typedoc
      - run: npx typedoc --readme none --exclude "**/*.test.ts" --excludeProtected --excludePrivate --excludeExternals src/ --out ../reference
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          clean: false
      - run: rm -r ../docs/reference
      - run: mv ../reference ../docs/
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'docs/reference'
          branch: gh-pages
          default_author: github_actions
          message: 'Updating docs'
