name: check
on: push
jobs:
  check-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    name: Check Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: install legacy pip for package
        working-directory: python
        run: pip install pip==21.1.2
      - name: pip
        working-directory: python
        run: pip install -r requirements/dev.txt
      - name: lint
        run: ./python/lint.sh
      - name: coverage
        run: PYTHONPATH=. coverage run --source python --branch --omit python/tests -m pytest
      - name: coverage report
        run: coverage report -m --fail-under 40
  check-php:
    runs-on: ubuntu-latest
    name: Check PHP
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          tools: phpunit:9.5.28, phpmd, phpcs, squizlabs/php_codesniffer
      - run: ./php/lint.sh
      - run: ./php/test.sh
      - run: php php/check.php php/clover.xml 10
