name: check
on: push
jobs:
  check-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.5']
    name: Check Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: pip install -r python/requirements/dev.txt
      - run: python/lint.sh
      - run: coverage run --source python --branch --omit python/tests -m pytest
      - run: coverage report -m --fail-under 40
  check-js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12' ]
    name: Check Node ${{ matrix.node }}
    defaults:
      run:
        working-directory: javascript
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      working-directory: scripts
      - run: yarn
      - run: yarn run eslint --ignore-pattern '.eslintrc.js' .
